apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  labels:
    app: nginx-2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: Always
        name: nginx-2
        ports:
        - containerPort: 80
          protocol: TCP
